name: Deploy to Scaleway Serverless Containers

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual trigger

env:
  REGISTRY_ENDPOINT: rg.nl-ams.scw.cloud
  IMAGE_NAME: mashplan-chat
  REGION: nl-ams

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_ENDPOINT }}
        username: nologin
        password: ${{ secrets.SCW_SECRET_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY_ENDPOINT }}/${{ secrets.SCW_REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
        platforms: linux/amd64

    - name: Deploy to Scaleway Serverless Container
      uses: httptoolkit/deploy-scaleway-serverless-container-action@v1
      with:
        container_id: ${{ secrets.SCW_CONTAINER_ID }}
        secret_key: ${{ secrets.SCW_SECRET_KEY }}
        registry_image_url: ${{ env.REGISTRY_ENDPOINT }}/${{ secrets.SCW_REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
        region: ${{ env.REGION }}
        timeout_seconds: 300

    - name: Deployment Summary
      run: |
        echo "🚀 Deployment completed successfully!"
        echo "✅ Image: ${{ env.REGISTRY_ENDPOINT }}/${{ secrets.SCW_REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest"
        echo "✅ Container ID: ${{ secrets.SCW_CONTAINER_ID }}"
        echo "✅ Region: ${{ env.REGION }}"
        echo ""
        echo "Your application should be available at your Scaleway container URL." 
